### ISSUE TITLE
Regarding Papers which Don't Seem to Fit Any of the Domains

### ISSUE THREAD

**Issue by aflah02** [styfeng/DataAug4NLP#7]
I recently came across this paper [CONAN - COunter NArratives through Nichesourcing: a Multilingual Dataset of Responses to Fight Online Hate Speech ](https://aclanthology.org/P19-1271.pdf) which uses paraphrasing as a data augmentation technique to generate more data samples but the paper is based on creating a new Dataset so I'm not sure which Domain would it be appropriate for. Any suggestions?

**Comment by vgtomahawk** [comment]
I think it could be placed under either "Mitigating bias" [Since the essential task underlying the dataset is generating or contrasting counter narratives given a hateful input text] or "Generation" [Since the actual task people would learn using something like this would be counter-narrative generation].

**Comment by aflah02** [comment]
Thanks @vgtomahawk these 2 do seem to fit it in. I feel Mitigating Bias might be more suitable here so I'll raise a pull request with that but if anyone feels otherwise feel free to comment

**Comment by vgtomahawk** [comment]
That sounds reasonable! Accepted the PR... Yeah there was another followup by the same authors in which they actually tried Generation rather than just analysis and discussed how it went...

**Comment by aflah02** [comment]
Thanks I'll check that work out too
